#ifndef _DB_GEN_H_
#define _DB_GEN_H_

// Database status codes
enum DATABASE_STATUS
{
  DBS_SUCCESS = 0,
  DBS_NOT_FOUND,
  DBS_DUPLICATE,
  DBS_NO_ROWS_PROCESSED,
  DBS_LOGON_ERR = 100,
  DBS_LOGOFF_ERR,
  DBS_OPEN_CURSOR_ERR,
  DBS_CLOSE_CURSOR_ERR,
  DBS_NO_CURSOR_ERR,
  DBS_PARSE_ERR,
  DBS_DEFINE_OUTPUT_VAR_ERR,
  DBS_DEFINE_INPUT_VAR_ERR,
  DBS_EXECUTE_ERR,
  DBS_COMMIT_ERR,
  DBS_ROLLBACK_ERR,
  DBS_FIELD_ERROR,
  DBS_RECEIVE_ERR,
  DBS_MESSAGE_ERR,
  DBS_MESSAGE_DBERR,
  DBS_COMM_ERR,
  DBS_PARAMETER_ERR,
  DBS_CONNECT_ERR,
  DBS_FETCH_MODE_ERR,
  DBS_INIT_ERR,
  DBS_DIRTY_WORD,
  DBS_DYN_SELECT_ERR,
  DBS_BANNED,
  DBS_FIELD_NO_ERROR = 200,
  DBS_FIELD_DATA_NULL,
  DBS_FIELD_DATA_TRUNCATE,
  DBS_FIELD_DATA_INVALID,
  DBS_FIELD_DATA_OVERFLOW,
  DBS_FIELD_BAD_DATATYPE,
  DBS_FIELD_STRING_OVERFLOW
};
typedef DATABASE_STATUS DBSTATUS;

#endif // _DB_GEN_H_
