#if !defined(sci_h)
#define sci_h

#include "sciobj.h"
#include "scifeatr.h"
#include "sciview.h"
#include "sciactor.h"
#include "scibtngp.h"
#include "scichkbx.h"
#include "scibuttn.h"
#include "scicycle.h"
#include "scidlgbx.h"
#include "scidplst.h"
#include "scievent.h"
#include "scigame.h"
#include "scigbox.h"
#include "scilist.h"
#include "scilstbx.h"
#include "scimotn.h"
#include "sciplane.h"
#include "scipopup.h"
#include "sciprop.h"
#include "scirail.h"
#include "scirect.h"
#include "sciroom.h"
#include "sciscrip.h"
#include "sciscrol.h"
#include "scislidr.h"
#include "scisong.h"
#include "scisound.h"
#include "scitext.h"

#include "globals.h"
#include "chat.h"
#include "rooms.h"
#include "rc.h"
#include "editbox.h"
#include "random.h"
#include "unused.h"

#endif
